version: '3'
services:
  golang:
    build: .
    container_name: 'golang'
    stdin_open: true
    tty: true
    hostname: 'golang'
    working_dir: '/app'
    volumes:
      - ..:/app
      - /app/.devcontainer
    command: /bin/bash

# docker compose up
# docker compose stop
# docker compose run golang fish --login
