version: '3'
x-ver: &NAME "webpack"
services:
  golang:
    build: .
    image: *NAME
    container_name: *NAME
    stdin_open: true
    tty: true
    hostname: *NAME
    working_dir: '/app'
    volumes:
      - ..:/app
      - /app/.devcontainer
    command: /usr/bin/bash

# docker compose build
# docker compose stop
# docker compose exec golang fish --login
